# define a makefile variable for java compiler
JCC =   javac
#params=" "
# define a makefile variable for compilation

# make runs first target which is default in this case

default: ./bin/LSApp.class:

./bin/LSApp.class: ./src/LSApp.java
        $(JCC) -d ./bin -g ./src/LSApp.java

# Remove all .class files , so that the next make rebuilds them

clean:
        $(RM) *.class

run1: .bin/LSApp.class
        java -cp ./bin LSApp $(params)

default: ./bin/LSBSApp.class:

./bin/LSApp.class: ./src/LSBSTApp.java
        $(JCC) -d ./bin -g ./src/LSBSTApp.java

# Remove all .class files , so that the next make rebuilds them


run2: .bin/LSApp.class
        java -cp ./bin LSBSTApp $(params)